import "./globals.css";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "SOTY 2024",
    description: "Generated by create next app"
};

export default function RootLayout(props: Readonly<{ children: React.ReactNode }>): React.JSX.Element {
    return (
        <html lang="en">
            <body className="antialiased">
                {props.children}
            </body>
        </html>
    );
}
